[package]
name = "alice-architecture-derive"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
heck = { workspace = true }
