[package]
name = "alice-di"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
alice-di-derive = { path = "../alice-di-derive" }
async-trait = { workspace = true }
anyhow = { workspace = true }

[features]
actix = ["alice-di-derive/actix"]
